/*Kreiranje nove tablice 'menze' u bazi studenti sa InnoDB storage enginom.*/
USE studenti;
CREATE TABLE `menze` (
  `idMenze` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) DEFAULT NULL,
  `adresa` VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (`idMenze`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;




/*Provjera trenutnog stanja sesijske varijable AUTOCOMMIT u bazi information_schema u tablici SESSION_VARIABLES.*/
SELECT * FROM `information_schema`.`SESSION_VARIABLES` 
WHERE `information_schema`.`SESSION_VARIABLES`.variable_name="autocommit";
/* ili */
SHOW VARIABLES WHERE variable_name = "autocommit";





/*Unos nove n-torke u tablicu menze (id je definiran sa autoinkrementom).*/
INSERT INTO menze (naziv, adresa) 
	VALUES ('Menza FSB', 'Ivana Lučića 5');

SELECT * FROM menze;




/*Pokušaj unosa dvije nove menze u bazu podataka, tablicu 'menze'. Opoziv unosa.*/
SET autocommit=0;
SHOW VARIABLES WHERE variable_name = "autocommit";
START TRANSACTION; 
	INSERT INTO menze (naziv, adresa) VALUES ('Menza Voltino', 'Konavoska 2');
	INSERT INTO menze (naziv, adresa) VALUES ('Menza Vrbik', 'Vrbik 8a');
	SELECT * FROM menze;
ROLLBACK;
SET autocommit=1;

SELECT * FROM menze;





/*Pokušaj unosa dvije nove menze u bazu podataka, tablicu 'menze'. Potvrda unosa.*/
SET autocommit=0;
START TRANSACTION; 
	SHOW VARIABLES WHERE variable_name = "autocommit";
	INSERT INTO menze (naziv, adresa) VALUES ('Menza Vrbik', 'Vrbik 8a');
	INSERT INTO menze (naziv, adresa) VALUES ('Menza Voltino', 'Konavoska 2');
COMMIT;
SET autocommit=1;
SELECT * FROM menze;




/*Pokušaj unosa dvije nove menze u bazu podataka, tablicu 'menze2' koja NIJE na InnoDB storage enginu. Opoziv unosa.*/
USE studenti;
CREATE TABLE `menze2` (
  `idMenze` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) DEFAULT NULL,
  `adresa` VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (`idMenze`)
) ENGINE=MYISAM  DEFAULT CHARSET=utf8;

SELECT * FROM menze2;
SET autocommit=0;
SHOW VARIABLES WHERE variable_name = "autocommit";
START TRANSACTION; 
	INSERT INTO menze2 (naziv, adresa) VALUES ('Menza Voltino', 'Konavoska 2');
	INSERT INTO menze2 (naziv, adresa) VALUES ('Menza Vrbik', 'Vrbik 8a');
ROLLBACK;
SET autocommit=1;
SELECT * FROM menze2;






/*Provjera kroz dvije sesije: potrebno je otvoriti u SQLyogu dvije sesije tj konekcije.*/
/*prva sesija*/
SET autocommit=0;
START TRANSACTION;
INSERT INTO menze (naziv, adresa) VALUES ('Menza Cassandra', 'Ul. Grada Vukovara 39');
SELECT * FROM menze;
			/*druga sesija*/
			SELECT * FROM menze;
/*prva sesija*/
COMMIT;
SET autocommit=1;
SELECT * FROM menze;
			/*druga sesija*/
			SELECT * FROM menze;
	
	
	
			
/*Opoziv DDL naredbe ne funkcionira.*/
SET autocommit=0;
BEGIN WORK;
	CREATE TABLE `menze3` (
	  `idMenze` INT(11) NOT NULL AUTO_INCREMENT,
	  `naziv` VARCHAR(50) DEFAULT NULL,
	  `adresa` VARCHAR(250) DEFAULT NULL,
	  PRIMARY KEY (`idMenze`)
	)  DEFAULT CHARSET=utf8;
ROLLBACK;
SET autocommit=1;



/* DEMO 2 */

/*U bazi radionice, potrebno je povećati koeficijent plaće radniku Kruljac Petru za 0.5, te ga za isti iznos smanjiti radniku Parlov Dini. 
Potvrditi samo promjenu koeficijenta za radnika Kruljca, promjenu za Parlova opovrgnuti.*/
USE radionica;
SELECT * FROM radnik 
	WHERE (prezimeRadnik = 'Parlov' AND imeRadnik='Dino')
		OR (prezimeRadnik = 'Kruljac' AND imeRadnik='Petar') ;
SET AUTOCOMMIT = 0; 
BEGIN; 
	UPDATE radnik
		SET koefPlaca=koefPlaca+0.5 
		WHERE prezimeRadnik = 'Kruljac' AND imeRadnik='Petar'; 
	SAVEPOINT tocka;
	UPDATE radnik
		SET koefPlaca=koefPlaca-0.5 
		WHERE prezimeRadnik = 'Parlov' AND imeRadnik='Dino'; 
	SELECT * FROM radnik WHERE (prezimeRadnik = 'Kruljac' AND imeRadnik='Petar') 
		OR (prezimeRadnik = 'Parlov' AND imeRadnik='Dino');
	ROLLBACK TO SAVEPOINT tocka;
	SELECT * FROM radnik WHERE (prezimeRadnik = 'Kruljac' AND imeRadnik='Petar') 
		OR (prezimeRadnik = 'Parlov' AND imeRadnik='Dino');
COMMIT; 
SET AUTOCOMMIT = 1;


SELECT * FROM radnik WHERE (prezimeRadnik = 'Kruljac' AND imeRadnik='Petar') 
		OR (prezimeRadnik = 'Parlov' AND imeRadnik='Dino');




/* DEMO 3 */

/*Pogreške u transakciji - izvršit će se sve SQL naredbe koje su izvedive.*/
BEGIN WORK;
INSERT INTO menze VALUES(10, 'naziv1', 'adresa1');
INSERT INTO menze VALUES(10, 'naziv2', 'adresa2');
COMMIT WORK;
SELECT * FROM menze;






/*Pogreške u transakciji - pogreške unutar transakcije kojima aplikacija ne rukuje na eksplicitan način. Djeljenje s nulom rezultirati će NULL vrijednostima. */
USE radionica;
SELECT * FROM radnik;

UPDATE radnik SET koefPlaca=koefplaca/0;

SELECT * FROM radnik;





/* Što ako 1000 insert naredbi pokrenemo za izvođenje, te nakon pola obavljenog posla dođe do prekida? Što ako su one sve dio jedne transakcije, te nakon pola obavljenog posla dođe do prekida? */
DELETE FROM menze;
SELECT * FROM menze;

SET AUTOCOMMIT = 0;
START TRANSACTION;
INSERT INTO menze (naziv, adresa) VALUES ('1', '1');
INSERT INTO menze (naziv, adresa) VALUES ('2', '2');
INSERT INTO menze (naziv, adresa) VALUES ('3', '3');
INSERT INTO menze (naziv, adresa) VALUES ('4', '4');
INSERT INTO menze (naziv, adresa) VALUES ('5', '5');
INSERT INTO menze (naziv, adresa) VALUES ('6', '6');
INSERT INTO menze (naziv, adresa) VALUES ('7', '7');
INSERT INTO menze (naziv, adresa) VALUES ('8', '8');
INSERT INTO menze (naziv, adresa) VALUES ('9', '9');
INSERT INTO menze (naziv, adresa) VALUES ('10', '10');
INSERT INTO menze (naziv, adresa) VALUES ('11', '11');
INSERT INTO menze (naziv, adresa) VALUES ('12', '12');
INSERT INTO menze (naziv, adresa) VALUES ('13', '13');
INSERT INTO menze (naziv, adresa) VALUES ('14', '14');
INSERT INTO menze (naziv, adresa) VALUES ('15', '15');
INSERT INTO menze (naziv, adresa) VALUES ('16', '16');
INSERT INTO menze (naziv, adresa) VALUES ('17', '17');
INSERT INTO menze (naziv, adresa) VALUES ('18', '18');
INSERT INTO menze (naziv, adresa) VALUES ('19', '19');
INSERT INTO menze (naziv, adresa) VALUES ('20', '20');
INSERT INTO menze (naziv, adresa) VALUES ('21', '21');
INSERT INTO menze (naziv, adresa) VALUES ('22', '22');
INSERT INTO menze (naziv, adresa) VALUES ('23', '23');
INSERT INTO menze (naziv, adresa) VALUES ('24', '24');
INSERT INTO menze (naziv, adresa) VALUES ('25', '25');
INSERT INTO menze (naziv, adresa) VALUES ('26', '26');
INSERT INTO menze (naziv, adresa) VALUES ('27', '27');
INSERT INTO menze (naziv, adresa) VALUES ('28', '28');
INSERT INTO menze (naziv, adresa) VALUES ('29', '29');
INSERT INTO menze (naziv, adresa) VALUES ('30', '30');
INSERT INTO menze (naziv, adresa) VALUES ('31', '31');
INSERT INTO menze (naziv, adresa) VALUES ('32', '32');
INSERT INTO menze (naziv, adresa) VALUES ('33', '33');
INSERT INTO menze (naziv, adresa) VALUES ('34', '34');
INSERT INTO menze (naziv, adresa) VALUES ('35', '35');
INSERT INTO menze (naziv, adresa) VALUES ('36', '36');
INSERT INTO menze (naziv, adresa) VALUES ('37', '37');
INSERT INTO menze (naziv, adresa) VALUES ('38', '38');
INSERT INTO menze (naziv, adresa) VALUES ('39', '39');
INSERT INTO menze (naziv, adresa) VALUES ('40', '40');
INSERT INTO menze (naziv, adresa) VALUES ('41', '41');
INSERT INTO menze (naziv, adresa) VALUES ('42', '42');
INSERT INTO menze (naziv, adresa) VALUES ('43', '43');
INSERT INTO menze (naziv, adresa) VALUES ('44', '44');
INSERT INTO menze (naziv, adresa) VALUES ('45', '45');
INSERT INTO menze (naziv, adresa) VALUES ('46', '46');
INSERT INTO menze (naziv, adresa) VALUES ('47', '47');
INSERT INTO menze (naziv, adresa) VALUES ('48', '48');
INSERT INTO menze (naziv, adresa) VALUES ('49', '49');
INSERT INTO menze (naziv, adresa) VALUES ('50', '50');
INSERT INTO menze (naziv, adresa) VALUES ('51', '51');
INSERT INTO menze (naziv, adresa) VALUES ('52', '52');
INSERT INTO menze (naziv, adresa) VALUES ('53', '53');
INSERT INTO menze (naziv, adresa) VALUES ('54', '54');
INSERT INTO menze (naziv, adresa) VALUES ('55', '55');
INSERT INTO menze (naziv, adresa) VALUES ('56', '56');
INSERT INTO menze (naziv, adresa) VALUES ('57', '57');
INSERT INTO menze (naziv, adresa) VALUES ('58', '58');
INSERT INTO menze (naziv, adresa) VALUES ('59', '59');
INSERT INTO menze (naziv, adresa) VALUES ('60', '60');
INSERT INTO menze (naziv, adresa) VALUES ('61', '61');
INSERT INTO menze (naziv, adresa) VALUES ('62', '62');
INSERT INTO menze (naziv, adresa) VALUES ('63', '63');
INSERT INTO menze (naziv, adresa) VALUES ('64', '64');
INSERT INTO menze (naziv, adresa) VALUES ('65', '65');
INSERT INTO menze (naziv, adresa) VALUES ('66', '66');
INSERT INTO menze (naziv, adresa) VALUES ('67', '67');
INSERT INTO menze (naziv, adresa) VALUES ('68', '68');
INSERT INTO menze (naziv, adresa) VALUES ('69', '69');
INSERT INTO menze (naziv, adresa) VALUES ('70', '70');
INSERT INTO menze (naziv, adresa) VALUES ('71', '71');
INSERT INTO menze (naziv, adresa) VALUES ('72', '72');
INSERT INTO menze (naziv, adresa) VALUES ('73', '73');
INSERT INTO menze (naziv, adresa) VALUES ('74', '74');
INSERT INTO menze (naziv, adresa) VALUES ('75', '75');
INSERT INTO menze (naziv, adresa) VALUES ('76', '76');
INSERT INTO menze (naziv, adresa) VALUES ('77', '77');
INSERT INTO menze (naziv, adresa) VALUES ('78', '78');
INSERT INTO menze (naziv, adresa) VALUES ('79', '79');
INSERT INTO menze (naziv, adresa) VALUES ('80', '80');
INSERT INTO menze (naziv, adresa) VALUES ('81', '81');
INSERT INTO menze (naziv, adresa) VALUES ('82', '82');
INSERT INTO menze (naziv, adresa) VALUES ('83', '83');
INSERT INTO menze (naziv, adresa) VALUES ('84', '84');
INSERT INTO menze (naziv, adresa) VALUES ('85', '85');
INSERT INTO menze (naziv, adresa) VALUES ('86', '86');
INSERT INTO menze (naziv, adresa) VALUES ('87', '87');
INSERT INTO menze (naziv, adresa) VALUES ('88', '88');
INSERT INTO menze (naziv, adresa) VALUES ('89', '89');
INSERT INTO menze (naziv, adresa) VALUES ('90', '90');
INSERT INTO menze (naziv, adresa) VALUES ('91', '91');
INSERT INTO menze (naziv, adresa) VALUES ('92', '92');
INSERT INTO menze (naziv, adresa) VALUES ('93', '93');
INSERT INTO menze (naziv, adresa) VALUES ('94', '94');
INSERT INTO menze (naziv, adresa) VALUES ('95', '95');
INSERT INTO menze (naziv, adresa) VALUES ('96', '96');
INSERT INTO menze (naziv, adresa) VALUES ('97', '97');
INSERT INTO menze (naziv, adresa) VALUES ('98', '98');
INSERT INTO menze (naziv, adresa) VALUES ('99', '99');
INSERT INTO menze (naziv, adresa) VALUES ('100', '100');
INSERT INTO menze (naziv, adresa) VALUES ('101', '101');
INSERT INTO menze (naziv, adresa) VALUES ('102', '102');
INSERT INTO menze (naziv, adresa) VALUES ('103', '103');
INSERT INTO menze (naziv, adresa) VALUES ('104', '104');
INSERT INTO menze (naziv, adresa) VALUES ('105', '105');
INSERT INTO menze (naziv, adresa) VALUES ('106', '106');
INSERT INTO menze (naziv, adresa) VALUES ('107', '107');
INSERT INTO menze (naziv, adresa) VALUES ('108', '108');
INSERT INTO menze (naziv, adresa) VALUES ('109', '109');
INSERT INTO menze (naziv, adresa) VALUES ('110', '110');
INSERT INTO menze (naziv, adresa) VALUES ('111', '111');
INSERT INTO menze (naziv, adresa) VALUES ('112', '112');
INSERT INTO menze (naziv, adresa) VALUES ('113', '113');
INSERT INTO menze (naziv, adresa) VALUES ('114', '114');
INSERT INTO menze (naziv, adresa) VALUES ('115', '115');
INSERT INTO menze (naziv, adresa) VALUES ('116', '116');
INSERT INTO menze (naziv, adresa) VALUES ('117', '117');
INSERT INTO menze (naziv, adresa) VALUES ('118', '118');
INSERT INTO menze (naziv, adresa) VALUES ('119', '119');
INSERT INTO menze (naziv, adresa) VALUES ('120', '120');
INSERT INTO menze (naziv, adresa) VALUES ('121', '121');
INSERT INTO menze (naziv, adresa) VALUES ('122', '122');
INSERT INTO menze (naziv, adresa) VALUES ('123', '123');
INSERT INTO menze (naziv, adresa) VALUES ('124', '124');
INSERT INTO menze (naziv, adresa) VALUES ('125', '125');
INSERT INTO menze (naziv, adresa) VALUES ('126', '126');
INSERT INTO menze (naziv, adresa) VALUES ('127', '127');
INSERT INTO menze (naziv, adresa) VALUES ('128', '128');
INSERT INTO menze (naziv, adresa) VALUES ('129', '129');
INSERT INTO menze (naziv, adresa) VALUES ('130', '130');
INSERT INTO menze (naziv, adresa) VALUES ('131', '131');
INSERT INTO menze (naziv, adresa) VALUES ('132', '132');
INSERT INTO menze (naziv, adresa) VALUES ('133', '133');
INSERT INTO menze (naziv, adresa) VALUES ('134', '134');
INSERT INTO menze (naziv, adresa) VALUES ('135', '135');
INSERT INTO menze (naziv, adresa) VALUES ('136', '136');
INSERT INTO menze (naziv, adresa) VALUES ('137', '137');
INSERT INTO menze (naziv, adresa) VALUES ('138', '138');
INSERT INTO menze (naziv, adresa) VALUES ('139', '139');
INSERT INTO menze (naziv, adresa) VALUES ('140', '140');
INSERT INTO menze (naziv, adresa) VALUES ('141', '141');
INSERT INTO menze (naziv, adresa) VALUES ('142', '142');
INSERT INTO menze (naziv, adresa) VALUES ('143', '143');
INSERT INTO menze (naziv, adresa) VALUES ('144', '144');
INSERT INTO menze (naziv, adresa) VALUES ('145', '145');
INSERT INTO menze (naziv, adresa) VALUES ('146', '146');
INSERT INTO menze (naziv, adresa) VALUES ('147', '147');
INSERT INTO menze (naziv, adresa) VALUES ('148', '148');
INSERT INTO menze (naziv, adresa) VALUES ('149', '149');
INSERT INTO menze (naziv, adresa) VALUES ('150', '150');
INSERT INTO menze (naziv, adresa) VALUES ('151', '151');
INSERT INTO menze (naziv, adresa) VALUES ('152', '152');
INSERT INTO menze (naziv, adresa) VALUES ('153', '153');
INSERT INTO menze (naziv, adresa) VALUES ('154', '154');
INSERT INTO menze (naziv, adresa) VALUES ('155', '155');
INSERT INTO menze (naziv, adresa) VALUES ('156', '156');
INSERT INTO menze (naziv, adresa) VALUES ('157', '157');
INSERT INTO menze (naziv, adresa) VALUES ('158', '158');
INSERT INTO menze (naziv, adresa) VALUES ('159', '159');
INSERT INTO menze (naziv, adresa) VALUES ('160', '160');
INSERT INTO menze (naziv, adresa) VALUES ('161', '161');
INSERT INTO menze (naziv, adresa) VALUES ('162', '162');
INSERT INTO menze (naziv, adresa) VALUES ('163', '163');
INSERT INTO menze (naziv, adresa) VALUES ('164', '164');
INSERT INTO menze (naziv, adresa) VALUES ('165', '165');
INSERT INTO menze (naziv, adresa) VALUES ('166', '166');
INSERT INTO menze (naziv, adresa) VALUES ('167', '167');
INSERT INTO menze (naziv, adresa) VALUES ('168', '168');
INSERT INTO menze (naziv, adresa) VALUES ('169', '169');
INSERT INTO menze (naziv, adresa) VALUES ('170', '170');
INSERT INTO menze (naziv, adresa) VALUES ('171', '171');
INSERT INTO menze (naziv, adresa) VALUES ('172', '172');
INSERT INTO menze (naziv, adresa) VALUES ('173', '173');
INSERT INTO menze (naziv, adresa) VALUES ('174', '174');
INSERT INTO menze (naziv, adresa) VALUES ('175', '175');
INSERT INTO menze (naziv, adresa) VALUES ('176', '176');
INSERT INTO menze (naziv, adresa) VALUES ('177', '177');
INSERT INTO menze (naziv, adresa) VALUES ('178', '178');
INSERT INTO menze (naziv, adresa) VALUES ('179', '179');
INSERT INTO menze (naziv, adresa) VALUES ('180', '180');
INSERT INTO menze (naziv, adresa) VALUES ('181', '181');
INSERT INTO menze (naziv, adresa) VALUES ('182', '182');
INSERT INTO menze (naziv, adresa) VALUES ('183', '183');
INSERT INTO menze (naziv, adresa) VALUES ('184', '184');
INSERT INTO menze (naziv, adresa) VALUES ('185', '185');
INSERT INTO menze (naziv, adresa) VALUES ('186', '186');
INSERT INTO menze (naziv, adresa) VALUES ('187', '187');
INSERT INTO menze (naziv, adresa) VALUES ('188', '188');
INSERT INTO menze (naziv, adresa) VALUES ('189', '189');
INSERT INTO menze (naziv, adresa) VALUES ('190', '190');
INSERT INTO menze (naziv, adresa) VALUES ('191', '191');
INSERT INTO menze (naziv, adresa) VALUES ('192', '192');
INSERT INTO menze (naziv, adresa) VALUES ('193', '193');
INSERT INTO menze (naziv, adresa) VALUES ('194', '194');
INSERT INTO menze (naziv, adresa) VALUES ('195', '195');
INSERT INTO menze (naziv, adresa) VALUES ('196', '196');
INSERT INTO menze (naziv, adresa) VALUES ('197', '197');
INSERT INTO menze (naziv, adresa) VALUES ('198', '198');
INSERT INTO menze (naziv, adresa) VALUES ('199', '199');
INSERT INTO menze (naziv, adresa) VALUES ('200', '200');
INSERT INTO menze (naziv, adresa) VALUES ('201', '201');
INSERT INTO menze (naziv, adresa) VALUES ('202', '202');
INSERT INTO menze (naziv, adresa) VALUES ('203', '203');
INSERT INTO menze (naziv, adresa) VALUES ('204', '204');
INSERT INTO menze (naziv, adresa) VALUES ('205', '205');
INSERT INTO menze (naziv, adresa) VALUES ('206', '206');
INSERT INTO menze (naziv, adresa) VALUES ('207', '207');
INSERT INTO menze (naziv, adresa) VALUES ('208', '208');
INSERT INTO menze (naziv, adresa) VALUES ('209', '209');
INSERT INTO menze (naziv, adresa) VALUES ('210', '210');
INSERT INTO menze (naziv, adresa) VALUES ('211', '211');
INSERT INTO menze (naziv, adresa) VALUES ('212', '212');
INSERT INTO menze (naziv, adresa) VALUES ('213', '213');
INSERT INTO menze (naziv, adresa) VALUES ('214', '214');
INSERT INTO menze (naziv, adresa) VALUES ('215', '215');
INSERT INTO menze (naziv, adresa) VALUES ('216', '216');
INSERT INTO menze (naziv, adresa) VALUES ('217', '217');
INSERT INTO menze (naziv, adresa) VALUES ('218', '218');
INSERT INTO menze (naziv, adresa) VALUES ('219', '219');
INSERT INTO menze (naziv, adresa) VALUES ('220', '220');
INSERT INTO menze (naziv, adresa) VALUES ('221', '221');
INSERT INTO menze (naziv, adresa) VALUES ('222', '222');
INSERT INTO menze (naziv, adresa) VALUES ('223', '223');
INSERT INTO menze (naziv, adresa) VALUES ('224', '224');
INSERT INTO menze (naziv, adresa) VALUES ('225', '225');
INSERT INTO menze (naziv, adresa) VALUES ('226', '226');
INSERT INTO menze (naziv, adresa) VALUES ('227', '227');
INSERT INTO menze (naziv, adresa) VALUES ('228', '228');
INSERT INTO menze (naziv, adresa) VALUES ('229', '229');
INSERT INTO menze (naziv, adresa) VALUES ('230', '230');
INSERT INTO menze (naziv, adresa) VALUES ('231', '231');
INSERT INTO menze (naziv, adresa) VALUES ('232', '232');
INSERT INTO menze (naziv, adresa) VALUES ('233', '233');
INSERT INTO menze (naziv, adresa) VALUES ('234', '234');
INSERT INTO menze (naziv, adresa) VALUES ('235', '235');
INSERT INTO menze (naziv, adresa) VALUES ('236', '236');
INSERT INTO menze (naziv, adresa) VALUES ('237', '237');
INSERT INTO menze (naziv, adresa) VALUES ('238', '238');
INSERT INTO menze (naziv, adresa) VALUES ('239', '239');
INSERT INTO menze (naziv, adresa) VALUES ('240', '240');
INSERT INTO menze (naziv, adresa) VALUES ('241', '241');
INSERT INTO menze (naziv, adresa) VALUES ('242', '242');
INSERT INTO menze (naziv, adresa) VALUES ('243', '243');
INSERT INTO menze (naziv, adresa) VALUES ('244', '244');
INSERT INTO menze (naziv, adresa) VALUES ('245', '245');
INSERT INTO menze (naziv, adresa) VALUES ('246', '246');
INSERT INTO menze (naziv, adresa) VALUES ('247', '247');
INSERT INTO menze (naziv, adresa) VALUES ('248', '248');
INSERT INTO menze (naziv, adresa) VALUES ('249', '249');
INSERT INTO menze (naziv, adresa) VALUES ('250', '250');
INSERT INTO menze (naziv, adresa) VALUES ('251', '251');
INSERT INTO menze (naziv, adresa) VALUES ('252', '252');
INSERT INTO menze (naziv, adresa) VALUES ('253', '253');
INSERT INTO menze (naziv, adresa) VALUES ('254', '254');
INSERT INTO menze (naziv, adresa) VALUES ('255', '255');
INSERT INTO menze (naziv, adresa) VALUES ('256', '256');
INSERT INTO menze (naziv, adresa) VALUES ('257', '257');
INSERT INTO menze (naziv, adresa) VALUES ('258', '258');
INSERT INTO menze (naziv, adresa) VALUES ('259', '259');
INSERT INTO menze (naziv, adresa) VALUES ('260', '260');
INSERT INTO menze (naziv, adresa) VALUES ('261', '261');
INSERT INTO menze (naziv, adresa) VALUES ('262', '262');
INSERT INTO menze (naziv, adresa) VALUES ('263', '263');
INSERT INTO menze (naziv, adresa) VALUES ('264', '264');
INSERT INTO menze (naziv, adresa) VALUES ('265', '265');
INSERT INTO menze (naziv, adresa) VALUES ('266', '266');
INSERT INTO menze (naziv, adresa) VALUES ('267', '267');
INSERT INTO menze (naziv, adresa) VALUES ('268', '268');
INSERT INTO menze (naziv, adresa) VALUES ('269', '269');
INSERT INTO menze (naziv, adresa) VALUES ('270', '270');
INSERT INTO menze (naziv, adresa) VALUES ('271', '271');
INSERT INTO menze (naziv, adresa) VALUES ('272', '272');
INSERT INTO menze (naziv, adresa) VALUES ('273', '273');
INSERT INTO menze (naziv, adresa) VALUES ('274', '274');
INSERT INTO menze (naziv, adresa) VALUES ('275', '275');
INSERT INTO menze (naziv, adresa) VALUES ('276', '276');
INSERT INTO menze (naziv, adresa) VALUES ('277', '277');
INSERT INTO menze (naziv, adresa) VALUES ('278', '278');
INSERT INTO menze (naziv, adresa) VALUES ('279', '279');
INSERT INTO menze (naziv, adresa) VALUES ('280', '280');
INSERT INTO menze (naziv, adresa) VALUES ('281', '281');
INSERT INTO menze (naziv, adresa) VALUES ('282', '282');
INSERT INTO menze (naziv, adresa) VALUES ('283', '283');
INSERT INTO menze (naziv, adresa) VALUES ('284', '284');
INSERT INTO menze (naziv, adresa) VALUES ('285', '285');
INSERT INTO menze (naziv, adresa) VALUES ('286', '286');
INSERT INTO menze (naziv, adresa) VALUES ('287', '287');
INSERT INTO menze (naziv, adresa) VALUES ('288', '288');
INSERT INTO menze (naziv, adresa) VALUES ('289', '289');
INSERT INTO menze (naziv, adresa) VALUES ('290', '290');
INSERT INTO menze (naziv, adresa) VALUES ('291', '291');
INSERT INTO menze (naziv, adresa) VALUES ('292', '292');
INSERT INTO menze (naziv, adresa) VALUES ('293', '293');
INSERT INTO menze (naziv, adresa) VALUES ('294', '294');
INSERT INTO menze (naziv, adresa) VALUES ('295', '295');
INSERT INTO menze (naziv, adresa) VALUES ('296', '296');
INSERT INTO menze (naziv, adresa) VALUES ('297', '297');
INSERT INTO menze (naziv, adresa) VALUES ('298', '298');
INSERT INTO menze (naziv, adresa) VALUES ('299', '299');
INSERT INTO menze (naziv, adresa) VALUES ('300', '300');
INSERT INTO menze (naziv, adresa) VALUES ('301', '301');
INSERT INTO menze (naziv, adresa) VALUES ('302', '302');
INSERT INTO menze (naziv, adresa) VALUES ('303', '303');
INSERT INTO menze (naziv, adresa) VALUES ('304', '304');
INSERT INTO menze (naziv, adresa) VALUES ('305', '305');
INSERT INTO menze (naziv, adresa) VALUES ('306', '306');
INSERT INTO menze (naziv, adresa) VALUES ('307', '307');
INSERT INTO menze (naziv, adresa) VALUES ('308', '308');
INSERT INTO menze (naziv, adresa) VALUES ('309', '309');
INSERT INTO menze (naziv, adresa) VALUES ('310', '310');
INSERT INTO menze (naziv, adresa) VALUES ('311', '311');
INSERT INTO menze (naziv, adresa) VALUES ('312', '312');
INSERT INTO menze (naziv, adresa) VALUES ('313', '313');
INSERT INTO menze (naziv, adresa) VALUES ('314', '314');
INSERT INTO menze (naziv, adresa) VALUES ('315', '315');
INSERT INTO menze (naziv, adresa) VALUES ('316', '316');
INSERT INTO menze (naziv, adresa) VALUES ('317', '317');
INSERT INTO menze (naziv, adresa) VALUES ('318', '318');
INSERT INTO menze (naziv, adresa) VALUES ('319', '319');
INSERT INTO menze (naziv, adresa) VALUES ('320', '320');
INSERT INTO menze (naziv, adresa) VALUES ('321', '321');
INSERT INTO menze (naziv, adresa) VALUES ('322', '322');
INSERT INTO menze (naziv, adresa) VALUES ('323', '323');
INSERT INTO menze (naziv, adresa) VALUES ('324', '324');
INSERT INTO menze (naziv, adresa) VALUES ('325', '325');
INSERT INTO menze (naziv, adresa) VALUES ('326', '326');
INSERT INTO menze (naziv, adresa) VALUES ('327', '327');
INSERT INTO menze (naziv, adresa) VALUES ('328', '328');
INSERT INTO menze (naziv, adresa) VALUES ('329', '329');
INSERT INTO menze (naziv, adresa) VALUES ('330', '330');
INSERT INTO menze (naziv, adresa) VALUES ('331', '331');
INSERT INTO menze (naziv, adresa) VALUES ('332', '332');
INSERT INTO menze (naziv, adresa) VALUES ('333', '333');
INSERT INTO menze (naziv, adresa) VALUES ('334', '334');
INSERT INTO menze (naziv, adresa) VALUES ('335', '335');
INSERT INTO menze (naziv, adresa) VALUES ('336', '336');
INSERT INTO menze (naziv, adresa) VALUES ('337', '337');
INSERT INTO menze (naziv, adresa) VALUES ('338', '338');
INSERT INTO menze (naziv, adresa) VALUES ('339', '339');
INSERT INTO menze (naziv, adresa) VALUES ('340', '340');
INSERT INTO menze (naziv, adresa) VALUES ('341', '341');
INSERT INTO menze (naziv, adresa) VALUES ('342', '342');
INSERT INTO menze (naziv, adresa) VALUES ('343', '343');
INSERT INTO menze (naziv, adresa) VALUES ('344', '344');
INSERT INTO menze (naziv, adresa) VALUES ('345', '345');
INSERT INTO menze (naziv, adresa) VALUES ('346', '346');
INSERT INTO menze (naziv, adresa) VALUES ('347', '347');
INSERT INTO menze (naziv, adresa) VALUES ('348', '348');
INSERT INTO menze (naziv, adresa) VALUES ('349', '349');
INSERT INTO menze (naziv, adresa) VALUES ('350', '350');
INSERT INTO menze (naziv, adresa) VALUES ('351', '351');
INSERT INTO menze (naziv, adresa) VALUES ('352', '352');
INSERT INTO menze (naziv, adresa) VALUES ('353', '353');
INSERT INTO menze (naziv, adresa) VALUES ('354', '354');
INSERT INTO menze (naziv, adresa) VALUES ('355', '355');
INSERT INTO menze (naziv, adresa) VALUES ('356', '356');
INSERT INTO menze (naziv, adresa) VALUES ('357', '357');
INSERT INTO menze (naziv, adresa) VALUES ('358', '358');
INSERT INTO menze (naziv, adresa) VALUES ('359', '359');
INSERT INTO menze (naziv, adresa) VALUES ('360', '360');
INSERT INTO menze (naziv, adresa) VALUES ('361', '361');
INSERT INTO menze (naziv, adresa) VALUES ('362', '362');
INSERT INTO menze (naziv, adresa) VALUES ('363', '363');
INSERT INTO menze (naziv, adresa) VALUES ('364', '364');
INSERT INTO menze (naziv, adresa) VALUES ('365', '365');
INSERT INTO menze (naziv, adresa) VALUES ('366', '366');
INSERT INTO menze (naziv, adresa) VALUES ('367', '367');
INSERT INTO menze (naziv, adresa) VALUES ('368', '368');
INSERT INTO menze (naziv, adresa) VALUES ('369', '369');
INSERT INTO menze (naziv, adresa) VALUES ('370', '370');
INSERT INTO menze (naziv, adresa) VALUES ('371', '371');
INSERT INTO menze (naziv, adresa) VALUES ('372', '372');
INSERT INTO menze (naziv, adresa) VALUES ('373', '373');
INSERT INTO menze (naziv, adresa) VALUES ('374', '374');
INSERT INTO menze (naziv, adresa) VALUES ('375', '375');
INSERT INTO menze (naziv, adresa) VALUES ('376', '376');
INSERT INTO menze (naziv, adresa) VALUES ('377', '377');
INSERT INTO menze (naziv, adresa) VALUES ('378', '378');
INSERT INTO menze (naziv, adresa) VALUES ('379', '379');
INSERT INTO menze (naziv, adresa) VALUES ('380', '380');
INSERT INTO menze (naziv, adresa) VALUES ('381', '381');
INSERT INTO menze (naziv, adresa) VALUES ('382', '382');
INSERT INTO menze (naziv, adresa) VALUES ('383', '383');
INSERT INTO menze (naziv, adresa) VALUES ('384', '384');
INSERT INTO menze (naziv, adresa) VALUES ('385', '385');
INSERT INTO menze (naziv, adresa) VALUES ('386', '386');
INSERT INTO menze (naziv, adresa) VALUES ('387', '387');
INSERT INTO menze (naziv, adresa) VALUES ('388', '388');
INSERT INTO menze (naziv, adresa) VALUES ('389', '389');
INSERT INTO menze (naziv, adresa) VALUES ('390', '390');
INSERT INTO menze (naziv, adresa) VALUES ('391', '391');
INSERT INTO menze (naziv, adresa) VALUES ('392', '392');
INSERT INTO menze (naziv, adresa) VALUES ('393', '393');
INSERT INTO menze (naziv, adresa) VALUES ('394', '394');
INSERT INTO menze (naziv, adresa) VALUES ('395', '395');
INSERT INTO menze (naziv, adresa) VALUES ('396', '396');
INSERT INTO menze (naziv, adresa) VALUES ('397', '397');
INSERT INTO menze (naziv, adresa) VALUES ('398', '398');
INSERT INTO menze (naziv, adresa) VALUES ('399', '399');
INSERT INTO menze (naziv, adresa) VALUES ('400', '400');
INSERT INTO menze (naziv, adresa) VALUES ('401', '401');
INSERT INTO menze (naziv, adresa) VALUES ('402', '402');
INSERT INTO menze (naziv, adresa) VALUES ('403', '403');
INSERT INTO menze (naziv, adresa) VALUES ('404', '404');
INSERT INTO menze (naziv, adresa) VALUES ('405', '405');
INSERT INTO menze (naziv, adresa) VALUES ('406', '406');
INSERT INTO menze (naziv, adresa) VALUES ('407', '407');
INSERT INTO menze (naziv, adresa) VALUES ('408', '408');
INSERT INTO menze (naziv, adresa) VALUES ('409', '409');
INSERT INTO menze (naziv, adresa) VALUES ('410', '410');
INSERT INTO menze (naziv, adresa) VALUES ('411', '411');
INSERT INTO menze (naziv, adresa) VALUES ('412', '412');
INSERT INTO menze (naziv, adresa) VALUES ('413', '413');
INSERT INTO menze (naziv, adresa) VALUES ('414', '414');
INSERT INTO menze (naziv, adresa) VALUES ('415', '415');
INSERT INTO menze (naziv, adresa) VALUES ('416', '416');
INSERT INTO menze (naziv, adresa) VALUES ('417', '417');
INSERT INTO menze (naziv, adresa) VALUES ('418', '418');
INSERT INTO menze (naziv, adresa) VALUES ('419', '419');
INSERT INTO menze (naziv, adresa) VALUES ('420', '420');
INSERT INTO menze (naziv, adresa) VALUES ('421', '421');
INSERT INTO menze (naziv, adresa) VALUES ('422', '422');
INSERT INTO menze (naziv, adresa) VALUES ('423', '423');
INSERT INTO menze (naziv, adresa) VALUES ('424', '424');
INSERT INTO menze (naziv, adresa) VALUES ('425', '425');
INSERT INTO menze (naziv, adresa) VALUES ('426', '426');
INSERT INTO menze (naziv, adresa) VALUES ('427', '427');
INSERT INTO menze (naziv, adresa) VALUES ('428', '428');
INSERT INTO menze (naziv, adresa) VALUES ('429', '429');
INSERT INTO menze (naziv, adresa) VALUES ('430', '430');
INSERT INTO menze (naziv, adresa) VALUES ('431', '431');
INSERT INTO menze (naziv, adresa) VALUES ('432', '432');
INSERT INTO menze (naziv, adresa) VALUES ('433', '433');
INSERT INTO menze (naziv, adresa) VALUES ('434', '434');
INSERT INTO menze (naziv, adresa) VALUES ('435', '435');
INSERT INTO menze (naziv, adresa) VALUES ('436', '436');
INSERT INTO menze (naziv, adresa) VALUES ('437', '437');
INSERT INTO menze (naziv, adresa) VALUES ('438', '438');
INSERT INTO menze (naziv, adresa) VALUES ('439', '439');
INSERT INTO menze (naziv, adresa) VALUES ('440', '440');
INSERT INTO menze (naziv, adresa) VALUES ('441', '441');
INSERT INTO menze (naziv, adresa) VALUES ('442', '442');
INSERT INTO menze (naziv, adresa) VALUES ('443', '443');
INSERT INTO menze (naziv, adresa) VALUES ('444', '444');
INSERT INTO menze (naziv, adresa) VALUES ('445', '445');
INSERT INTO menze (naziv, adresa) VALUES ('446', '446');
INSERT INTO menze (naziv, adresa) VALUES ('447', '447');
INSERT INTO menze (naziv, adresa) VALUES ('448', '448');
INSERT INTO menze (naziv, adresa) VALUES ('449', '449');
INSERT INTO menze (naziv, adresa) VALUES ('450', '450');
INSERT INTO menze (naziv, adresa) VALUES ('451', '451');
INSERT INTO menze (naziv, adresa) VALUES ('452', '452');
INSERT INTO menze (naziv, adresa) VALUES ('453', '453');
INSERT INTO menze (naziv, adresa) VALUES ('454', '454');
INSERT INTO menze (naziv, adresa) VALUES ('455', '455');
INSERT INTO menze (naziv, adresa) VALUES ('456', '456');
INSERT INTO menze (naziv, adresa) VALUES ('457', '457');
INSERT INTO menze (naziv, adresa) VALUES ('458', '458');
INSERT INTO menze (naziv, adresa) VALUES ('459', '459');
INSERT INTO menze (naziv, adresa) VALUES ('460', '460');
INSERT INTO menze (naziv, adresa) VALUES ('461', '461');
INSERT INTO menze (naziv, adresa) VALUES ('462', '462');
INSERT INTO menze (naziv, adresa) VALUES ('463', '463');
INSERT INTO menze (naziv, adresa) VALUES ('464', '464');
INSERT INTO menze (naziv, adresa) VALUES ('465', '465');
INSERT INTO menze (naziv, adresa) VALUES ('466', '466');
INSERT INTO menze (naziv, adresa) VALUES ('467', '467');
INSERT INTO menze (naziv, adresa) VALUES ('468', '468');
INSERT INTO menze (naziv, adresa) VALUES ('469', '469');
INSERT INTO menze (naziv, adresa) VALUES ('470', '470');
INSERT INTO menze (naziv, adresa) VALUES ('471', '471');
INSERT INTO menze (naziv, adresa) VALUES ('472', '472');
INSERT INTO menze (naziv, adresa) VALUES ('473', '473');
INSERT INTO menze (naziv, adresa) VALUES ('474', '474');
INSERT INTO menze (naziv, adresa) VALUES ('475', '475');
INSERT INTO menze (naziv, adresa) VALUES ('476', '476');
INSERT INTO menze (naziv, adresa) VALUES ('477', '477');
INSERT INTO menze (naziv, adresa) VALUES ('478', '478');
INSERT INTO menze (naziv, adresa) VALUES ('479', '479');
INSERT INTO menze (naziv, adresa) VALUES ('480', '480');
INSERT INTO menze (naziv, adresa) VALUES ('481', '481');
INSERT INTO menze (naziv, adresa) VALUES ('482', '482');
INSERT INTO menze (naziv, adresa) VALUES ('483', '483');
INSERT INTO menze (naziv, adresa) VALUES ('484', '484');
INSERT INTO menze (naziv, adresa) VALUES ('485', '485');
INSERT INTO menze (naziv, adresa) VALUES ('486', '486');
INSERT INTO menze (naziv, adresa) VALUES ('487', '487');
INSERT INTO menze (naziv, adresa) VALUES ('488', '488');
INSERT INTO menze (naziv, adresa) VALUES ('489', '489');
INSERT INTO menze (naziv, adresa) VALUES ('490', '490');
INSERT INTO menze (naziv, adresa) VALUES ('491', '491');
INSERT INTO menze (naziv, adresa) VALUES ('492', '492');
INSERT INTO menze (naziv, adresa) VALUES ('493', '493');
INSERT INTO menze (naziv, adresa) VALUES ('494', '494');
INSERT INTO menze (naziv, adresa) VALUES ('495', '495');
INSERT INTO menze (naziv, adresa) VALUES ('496', '496');
INSERT INTO menze (naziv, adresa) VALUES ('497', '497');
INSERT INTO menze (naziv, adresa) VALUES ('498', '498');
INSERT INTO menze (naziv, adresa) VALUES ('499', '499');
INSERT INTO menze (naziv, adresa) VALUES ('500', '500');
INSERT INTO menze (naziv, adresa) VALUES ('501', '501');
INSERT INTO menze (naziv, adresa) VALUES ('502', '502');
INSERT INTO menze (naziv, adresa) VALUES ('503', '503');
INSERT INTO menze (naziv, adresa) VALUES ('504', '504');
INSERT INTO menze (naziv, adresa) VALUES ('505', '505');
INSERT INTO menze (naziv, adresa) VALUES ('506', '506');
INSERT INTO menze (naziv, adresa) VALUES ('507', '507');
INSERT INTO menze (naziv, adresa) VALUES ('508', '508');
INSERT INTO menze (naziv, adresa) VALUES ('509', '509');
INSERT INTO menze (naziv, adresa) VALUES ('510', '510');
INSERT INTO menze (naziv, adresa) VALUES ('511', '511');
INSERT INTO menze (naziv, adresa) VALUES ('512', '512');
INSERT INTO menze (naziv, adresa) VALUES ('513', '513');
INSERT INTO menze (naziv, adresa) VALUES ('514', '514');
INSERT INTO menze (naziv, adresa) VALUES ('515', '515');
INSERT INTO menze (naziv, adresa) VALUES ('516', '516');
INSERT INTO menze (naziv, adresa) VALUES ('517', '517');
INSERT INTO menze (naziv, adresa) VALUES ('518', '518');
INSERT INTO menze (naziv, adresa) VALUES ('519', '519');
INSERT INTO menze (naziv, adresa) VALUES ('520', '520');
INSERT INTO menze (naziv, adresa) VALUES ('521', '521');
INSERT INTO menze (naziv, adresa) VALUES ('522', '522');
INSERT INTO menze (naziv, adresa) VALUES ('523', '523');
INSERT INTO menze (naziv, adresa) VALUES ('524', '524');
INSERT INTO menze (naziv, adresa) VALUES ('525', '525');
INSERT INTO menze (naziv, adresa) VALUES ('526', '526');
INSERT INTO menze (naziv, adresa) VALUES ('527', '527');
INSERT INTO menze (naziv, adresa) VALUES ('528', '528');
INSERT INTO menze (naziv, adresa) VALUES ('529', '529');
INSERT INTO menze (naziv, adresa) VALUES ('530', '530');
INSERT INTO menze (naziv, adresa) VALUES ('531', '531');
INSERT INTO menze (naziv, adresa) VALUES ('532', '532');
INSERT INTO menze (naziv, adresa) VALUES ('533', '533');
INSERT INTO menze (naziv, adresa) VALUES ('534', '534');
INSERT INTO menze (naziv, adresa) VALUES ('535', '535');
INSERT INTO menze (naziv, adresa) VALUES ('536', '536');
INSERT INTO menze (naziv, adresa) VALUES ('537', '537');
INSERT INTO menze (naziv, adresa) VALUES ('538', '538');
INSERT INTO menze (naziv, adresa) VALUES ('539', '539');
INSERT INTO menze (naziv, adresa) VALUES ('540', '540');
INSERT INTO menze (naziv, adresa) VALUES ('541', '541');
INSERT INTO menze (naziv, adresa) VALUES ('542', '542');
INSERT INTO menze (naziv, adresa) VALUES ('543', '543');
INSERT INTO menze (naziv, adresa) VALUES ('544', '544');
INSERT INTO menze (naziv, adresa) VALUES ('545', '545');
INSERT INTO menze (naziv, adresa) VALUES ('546', '546');
INSERT INTO menze (naziv, adresa) VALUES ('547', '547');
INSERT INTO menze (naziv, adresa) VALUES ('548', '548');
INSERT INTO menze (naziv, adresa) VALUES ('549', '549');
INSERT INTO menze (naziv, adresa) VALUES ('550', '550');
INSERT INTO menze (naziv, adresa) VALUES ('551', '551');
INSERT INTO menze (naziv, adresa) VALUES ('552', '552');
INSERT INTO menze (naziv, adresa) VALUES ('553', '553');
INSERT INTO menze (naziv, adresa) VALUES ('554', '554');
INSERT INTO menze (naziv, adresa) VALUES ('555', '555');
INSERT INTO menze (naziv, adresa) VALUES ('556', '556');
INSERT INTO menze (naziv, adresa) VALUES ('557', '557');
INSERT INTO menze (naziv, adresa) VALUES ('558', '558');
INSERT INTO menze (naziv, adresa) VALUES ('559', '559');
INSERT INTO menze (naziv, adresa) VALUES ('560', '560');
INSERT INTO menze (naziv, adresa) VALUES ('561', '561');
INSERT INTO menze (naziv, adresa) VALUES ('562', '562');
INSERT INTO menze (naziv, adresa) VALUES ('563', '563');
INSERT INTO menze (naziv, adresa) VALUES ('564', '564');
INSERT INTO menze (naziv, adresa) VALUES ('565', '565');
INSERT INTO menze (naziv, adresa) VALUES ('566', '566');
INSERT INTO menze (naziv, adresa) VALUES ('567', '567');
INSERT INTO menze (naziv, adresa) VALUES ('568', '568');
INSERT INTO menze (naziv, adresa) VALUES ('569', '569');
INSERT INTO menze (naziv, adresa) VALUES ('570', '570');
INSERT INTO menze (naziv, adresa) VALUES ('571', '571');
INSERT INTO menze (naziv, adresa) VALUES ('572', '572');
INSERT INTO menze (naziv, adresa) VALUES ('573', '573');
INSERT INTO menze (naziv, adresa) VALUES ('574', '574');
INSERT INTO menze (naziv, adresa) VALUES ('575', '575');
INSERT INTO menze (naziv, adresa) VALUES ('576', '576');
INSERT INTO menze (naziv, adresa) VALUES ('577', '577');
INSERT INTO menze (naziv, adresa) VALUES ('578', '578');
INSERT INTO menze (naziv, adresa) VALUES ('579', '579');
INSERT INTO menze (naziv, adresa) VALUES ('580', '580');
INSERT INTO menze (naziv, adresa) VALUES ('581', '581');
INSERT INTO menze (naziv, adresa) VALUES ('582', '582');
INSERT INTO menze (naziv, adresa) VALUES ('583', '583');
INSERT INTO menze (naziv, adresa) VALUES ('584', '584');
INSERT INTO menze (naziv, adresa) VALUES ('585', '585');
INSERT INTO menze (naziv, adresa) VALUES ('586', '586');
INSERT INTO menze (naziv, adresa) VALUES ('587', '587');
INSERT INTO menze (naziv, adresa) VALUES ('588', '588');
INSERT INTO menze (naziv, adresa) VALUES ('589', '589');
INSERT INTO menze (naziv, adresa) VALUES ('590', '590');
INSERT INTO menze (naziv, adresa) VALUES ('591', '591');
INSERT INTO menze (naziv, adresa) VALUES ('592', '592');
INSERT INTO menze (naziv, adresa) VALUES ('593', '593');
INSERT INTO menze (naziv, adresa) VALUES ('594', '594');
INSERT INTO menze (naziv, adresa) VALUES ('595', '595');
INSERT INTO menze (naziv, adresa) VALUES ('596', '596');
INSERT INTO menze (naziv, adresa) VALUES ('597', '597');
INSERT INTO menze (naziv, adresa) VALUES ('598', '598');
INSERT INTO menze (naziv, adresa) VALUES ('599', '599');
INSERT INTO menze (naziv, adresa) VALUES ('600', '600');
INSERT INTO menze (naziv, adresa) VALUES ('601', '601');
INSERT INTO menze (naziv, adresa) VALUES ('602', '602');
INSERT INTO menze (naziv, adresa) VALUES ('603', '603');
INSERT INTO menze (naziv, adresa) VALUES ('604', '604');
INSERT INTO menze (naziv, adresa) VALUES ('605', '605');
INSERT INTO menze (naziv, adresa) VALUES ('606', '606');
INSERT INTO menze (naziv, adresa) VALUES ('607', '607');
INSERT INTO menze (naziv, adresa) VALUES ('608', '608');
INSERT INTO menze (naziv, adresa) VALUES ('609', '609');
INSERT INTO menze (naziv, adresa) VALUES ('610', '610');
INSERT INTO menze (naziv, adresa) VALUES ('611', '611');
INSERT INTO menze (naziv, adresa) VALUES ('612', '612');
INSERT INTO menze (naziv, adresa) VALUES ('613', '613');
INSERT INTO menze (naziv, adresa) VALUES ('614', '614');
INSERT INTO menze (naziv, adresa) VALUES ('615', '615');
INSERT INTO menze (naziv, adresa) VALUES ('616', '616');
INSERT INTO menze (naziv, adresa) VALUES ('617', '617');
INSERT INTO menze (naziv, adresa) VALUES ('618', '618');
INSERT INTO menze (naziv, adresa) VALUES ('619', '619');
INSERT INTO menze (naziv, adresa) VALUES ('620', '620');
INSERT INTO menze (naziv, adresa) VALUES ('621', '621');
INSERT INTO menze (naziv, adresa) VALUES ('622', '622');
INSERT INTO menze (naziv, adresa) VALUES ('623', '623');
INSERT INTO menze (naziv, adresa) VALUES ('624', '624');
INSERT INTO menze (naziv, adresa) VALUES ('625', '625');
INSERT INTO menze (naziv, adresa) VALUES ('626', '626');
INSERT INTO menze (naziv, adresa) VALUES ('627', '627');
INSERT INTO menze (naziv, adresa) VALUES ('628', '628');
INSERT INTO menze (naziv, adresa) VALUES ('629', '629');
INSERT INTO menze (naziv, adresa) VALUES ('630', '630');
INSERT INTO menze (naziv, adresa) VALUES ('631', '631');
INSERT INTO menze (naziv, adresa) VALUES ('632', '632');
INSERT INTO menze (naziv, adresa) VALUES ('633', '633');
INSERT INTO menze (naziv, adresa) VALUES ('634', '634');
INSERT INTO menze (naziv, adresa) VALUES ('635', '635');
INSERT INTO menze (naziv, adresa) VALUES ('636', '636');
INSERT INTO menze (naziv, adresa) VALUES ('637', '637');
INSERT INTO menze (naziv, adresa) VALUES ('638', '638');
INSERT INTO menze (naziv, adresa) VALUES ('639', '639');
INSERT INTO menze (naziv, adresa) VALUES ('640', '640');
INSERT INTO menze (naziv, adresa) VALUES ('641', '641');
INSERT INTO menze (naziv, adresa) VALUES ('642', '642');
INSERT INTO menze (naziv, adresa) VALUES ('643', '643');
INSERT INTO menze (naziv, adresa) VALUES ('644', '644');
INSERT INTO menze (naziv, adresa) VALUES ('645', '645');
INSERT INTO menze (naziv, adresa) VALUES ('646', '646');
INSERT INTO menze (naziv, adresa) VALUES ('647', '647');
INSERT INTO menze (naziv, adresa) VALUES ('648', '648');
INSERT INTO menze (naziv, adresa) VALUES ('649', '649');
INSERT INTO menze (naziv, adresa) VALUES ('650', '650');
INSERT INTO menze (naziv, adresa) VALUES ('651', '651');
INSERT INTO menze (naziv, adresa) VALUES ('652', '652');
INSERT INTO menze (naziv, adresa) VALUES ('653', '653');
INSERT INTO menze (naziv, adresa) VALUES ('654', '654');
INSERT INTO menze (naziv, adresa) VALUES ('655', '655');
INSERT INTO menze (naziv, adresa) VALUES ('656', '656');
INSERT INTO menze (naziv, adresa) VALUES ('657', '657');
INSERT INTO menze (naziv, adresa) VALUES ('658', '658');
INSERT INTO menze (naziv, adresa) VALUES ('659', '659');
INSERT INTO menze (naziv, adresa) VALUES ('660', '660');
INSERT INTO menze (naziv, adresa) VALUES ('661', '661');
INSERT INTO menze (naziv, adresa) VALUES ('662', '662');
INSERT INTO menze (naziv, adresa) VALUES ('663', '663');
INSERT INTO menze (naziv, adresa) VALUES ('664', '664');
INSERT INTO menze (naziv, adresa) VALUES ('665', '665');
INSERT INTO menze (naziv, adresa) VALUES ('666', '666');
INSERT INTO menze (naziv, adresa) VALUES ('667', '667');
INSERT INTO menze (naziv, adresa) VALUES ('668', '668');
INSERT INTO menze (naziv, adresa) VALUES ('669', '669');
INSERT INTO menze (naziv, adresa) VALUES ('670', '670');
INSERT INTO menze (naziv, adresa) VALUES ('671', '671');
INSERT INTO menze (naziv, adresa) VALUES ('672', '672');
INSERT INTO menze (naziv, adresa) VALUES ('673', '673');
INSERT INTO menze (naziv, adresa) VALUES ('674', '674');
INSERT INTO menze (naziv, adresa) VALUES ('675', '675');
INSERT INTO menze (naziv, adresa) VALUES ('676', '676');
INSERT INTO menze (naziv, adresa) VALUES ('677', '677');
INSERT INTO menze (naziv, adresa) VALUES ('678', '678');
INSERT INTO menze (naziv, adresa) VALUES ('679', '679');
INSERT INTO menze (naziv, adresa) VALUES ('680', '680');
INSERT INTO menze (naziv, adresa) VALUES ('681', '681');
INSERT INTO menze (naziv, adresa) VALUES ('682', '682');
INSERT INTO menze (naziv, adresa) VALUES ('683', '683');
INSERT INTO menze (naziv, adresa) VALUES ('684', '684');
INSERT INTO menze (naziv, adresa) VALUES ('685', '685');
INSERT INTO menze (naziv, adresa) VALUES ('686', '686');
INSERT INTO menze (naziv, adresa) VALUES ('687', '687');
INSERT INTO menze (naziv, adresa) VALUES ('688', '688');
INSERT INTO menze (naziv, adresa) VALUES ('689', '689');
INSERT INTO menze (naziv, adresa) VALUES ('690', '690');
INSERT INTO menze (naziv, adresa) VALUES ('691', '691');
INSERT INTO menze (naziv, adresa) VALUES ('692', '692');
INSERT INTO menze (naziv, adresa) VALUES ('693', '693');
INSERT INTO menze (naziv, adresa) VALUES ('694', '694');
INSERT INTO menze (naziv, adresa) VALUES ('695', '695');
INSERT INTO menze (naziv, adresa) VALUES ('696', '696');
INSERT INTO menze (naziv, adresa) VALUES ('697', '697');
INSERT INTO menze (naziv, adresa) VALUES ('698', '698');
INSERT INTO menze (naziv, adresa) VALUES ('699', '699');
INSERT INTO menze (naziv, adresa) VALUES ('700', '700');
INSERT INTO menze (naziv, adresa) VALUES ('701', '701');
INSERT INTO menze (naziv, adresa) VALUES ('702', '702');
INSERT INTO menze (naziv, adresa) VALUES ('703', '703');
INSERT INTO menze (naziv, adresa) VALUES ('704', '704');
INSERT INTO menze (naziv, adresa) VALUES ('705', '705');
INSERT INTO menze (naziv, adresa) VALUES ('706', '706');
INSERT INTO menze (naziv, adresa) VALUES ('707', '707');
INSERT INTO menze (naziv, adresa) VALUES ('708', '708');
INSERT INTO menze (naziv, adresa) VALUES ('709', '709');
INSERT INTO menze (naziv, adresa) VALUES ('710', '710');
INSERT INTO menze (naziv, adresa) VALUES ('711', '711');
INSERT INTO menze (naziv, adresa) VALUES ('712', '712');
INSERT INTO menze (naziv, adresa) VALUES ('713', '713');
INSERT INTO menze (naziv, adresa) VALUES ('714', '714');
INSERT INTO menze (naziv, adresa) VALUES ('715', '715');
INSERT INTO menze (naziv, adresa) VALUES ('716', '716');
INSERT INTO menze (naziv, adresa) VALUES ('717', '717');
INSERT INTO menze (naziv, adresa) VALUES ('718', '718');
INSERT INTO menze (naziv, adresa) VALUES ('719', '719');
INSERT INTO menze (naziv, adresa) VALUES ('720', '720');
INSERT INTO menze (naziv, adresa) VALUES ('721', '721');
INSERT INTO menze (naziv, adresa) VALUES ('722', '722');
INSERT INTO menze (naziv, adresa) VALUES ('723', '723');
INSERT INTO menze (naziv, adresa) VALUES ('724', '724');
INSERT INTO menze (naziv, adresa) VALUES ('725', '725');
INSERT INTO menze (naziv, adresa) VALUES ('726', '726');
INSERT INTO menze (naziv, adresa) VALUES ('727', '727');
INSERT INTO menze (naziv, adresa) VALUES ('728', '728');
INSERT INTO menze (naziv, adresa) VALUES ('729', '729');
INSERT INTO menze (naziv, adresa) VALUES ('730', '730');
INSERT INTO menze (naziv, adresa) VALUES ('731', '731');
INSERT INTO menze (naziv, adresa) VALUES ('732', '732');
INSERT INTO menze (naziv, adresa) VALUES ('733', '733');
INSERT INTO menze (naziv, adresa) VALUES ('734', '734');
INSERT INTO menze (naziv, adresa) VALUES ('735', '735');
INSERT INTO menze (naziv, adresa) VALUES ('736', '736');
INSERT INTO menze (naziv, adresa) VALUES ('737', '737');
INSERT INTO menze (naziv, adresa) VALUES ('738', '738');
INSERT INTO menze (naziv, adresa) VALUES ('739', '739');
INSERT INTO menze (naziv, adresa) VALUES ('740', '740');
INSERT INTO menze (naziv, adresa) VALUES ('741', '741');
INSERT INTO menze (naziv, adresa) VALUES ('742', '742');
INSERT INTO menze (naziv, adresa) VALUES ('743', '743');
INSERT INTO menze (naziv, adresa) VALUES ('744', '744');
INSERT INTO menze (naziv, adresa) VALUES ('745', '745');
INSERT INTO menze (naziv, adresa) VALUES ('746', '746');
INSERT INTO menze (naziv, adresa) VALUES ('747', '747');
INSERT INTO menze (naziv, adresa) VALUES ('748', '748');
INSERT INTO menze (naziv, adresa) VALUES ('749', '749');
INSERT INTO menze (naziv, adresa) VALUES ('750', '750');
INSERT INTO menze (naziv, adresa) VALUES ('751', '751');
INSERT INTO menze (naziv, adresa) VALUES ('752', '752');
INSERT INTO menze (naziv, adresa) VALUES ('753', '753');
INSERT INTO menze (naziv, adresa) VALUES ('754', '754');
INSERT INTO menze (naziv, adresa) VALUES ('755', '755');
INSERT INTO menze (naziv, adresa) VALUES ('756', '756');
INSERT INTO menze (naziv, adresa) VALUES ('757', '757');
INSERT INTO menze (naziv, adresa) VALUES ('758', '758');
INSERT INTO menze (naziv, adresa) VALUES ('759', '759');
INSERT INTO menze (naziv, adresa) VALUES ('760', '760');
INSERT INTO menze (naziv, adresa) VALUES ('761', '761');
INSERT INTO menze (naziv, adresa) VALUES ('762', '762');
INSERT INTO menze (naziv, adresa) VALUES ('763', '763');
INSERT INTO menze (naziv, adresa) VALUES ('764', '764');
INSERT INTO menze (naziv, adresa) VALUES ('765', '765');
INSERT INTO menze (naziv, adresa) VALUES ('766', '766');
INSERT INTO menze (naziv, adresa) VALUES ('767', '767');
INSERT INTO menze (naziv, adresa) VALUES ('768', '768');
INSERT INTO menze (naziv, adresa) VALUES ('769', '769');
INSERT INTO menze (naziv, adresa) VALUES ('770', '770');
INSERT INTO menze (naziv, adresa) VALUES ('771', '771');
INSERT INTO menze (naziv, adresa) VALUES ('772', '772');
INSERT INTO menze (naziv, adresa) VALUES ('773', '773');
INSERT INTO menze (naziv, adresa) VALUES ('774', '774');
INSERT INTO menze (naziv, adresa) VALUES ('775', '775');
INSERT INTO menze (naziv, adresa) VALUES ('776', '776');
INSERT INTO menze (naziv, adresa) VALUES ('777', '777');
INSERT INTO menze (naziv, adresa) VALUES ('778', '778');
INSERT INTO menze (naziv, adresa) VALUES ('779', '779');
INSERT INTO menze (naziv, adresa) VALUES ('780', '780');
INSERT INTO menze (naziv, adresa) VALUES ('781', '781');
INSERT INTO menze (naziv, adresa) VALUES ('782', '782');
INSERT INTO menze (naziv, adresa) VALUES ('783', '783');
INSERT INTO menze (naziv, adresa) VALUES ('784', '784');
INSERT INTO menze (naziv, adresa) VALUES ('785', '785');
INSERT INTO menze (naziv, adresa) VALUES ('786', '786');
INSERT INTO menze (naziv, adresa) VALUES ('787', '787');
INSERT INTO menze (naziv, adresa) VALUES ('788', '788');
INSERT INTO menze (naziv, adresa) VALUES ('789', '789');
INSERT INTO menze (naziv, adresa) VALUES ('790', '790');
INSERT INTO menze (naziv, adresa) VALUES ('791', '791');
INSERT INTO menze (naziv, adresa) VALUES ('792', '792');
INSERT INTO menze (naziv, adresa) VALUES ('793', '793');
INSERT INTO menze (naziv, adresa) VALUES ('794', '794');
INSERT INTO menze (naziv, adresa) VALUES ('795', '795');
INSERT INTO menze (naziv, adresa) VALUES ('796', '796');
INSERT INTO menze (naziv, adresa) VALUES ('797', '797');
INSERT INTO menze (naziv, adresa) VALUES ('798', '798');
INSERT INTO menze (naziv, adresa) VALUES ('799', '799');
INSERT INTO menze (naziv, adresa) VALUES ('800', '800');
INSERT INTO menze (naziv, adresa) VALUES ('801', '801');
INSERT INTO menze (naziv, adresa) VALUES ('802', '802');
INSERT INTO menze (naziv, adresa) VALUES ('803', '803');
INSERT INTO menze (naziv, adresa) VALUES ('804', '804');
INSERT INTO menze (naziv, adresa) VALUES ('805', '805');
INSERT INTO menze (naziv, adresa) VALUES ('806', '806');
INSERT INTO menze (naziv, adresa) VALUES ('807', '807');
INSERT INTO menze (naziv, adresa) VALUES ('808', '808');
INSERT INTO menze (naziv, adresa) VALUES ('809', '809');
INSERT INTO menze (naziv, adresa) VALUES ('810', '810');
INSERT INTO menze (naziv, adresa) VALUES ('811', '811');
INSERT INTO menze (naziv, adresa) VALUES ('812', '812');
INSERT INTO menze (naziv, adresa) VALUES ('813', '813');
INSERT INTO menze (naziv, adresa) VALUES ('814', '814');
INSERT INTO menze (naziv, adresa) VALUES ('815', '815');
INSERT INTO menze (naziv, adresa) VALUES ('816', '816');
INSERT INTO menze (naziv, adresa) VALUES ('817', '817');
INSERT INTO menze (naziv, adresa) VALUES ('818', '818');
INSERT INTO menze (naziv, adresa) VALUES ('819', '819');
INSERT INTO menze (naziv, adresa) VALUES ('820', '820');
INSERT INTO menze (naziv, adresa) VALUES ('821', '821');
INSERT INTO menze (naziv, adresa) VALUES ('822', '822');
INSERT INTO menze (naziv, adresa) VALUES ('823', '823');
INSERT INTO menze (naziv, adresa) VALUES ('824', '824');
INSERT INTO menze (naziv, adresa) VALUES ('825', '825');
INSERT INTO menze (naziv, adresa) VALUES ('826', '826');
INSERT INTO menze (naziv, adresa) VALUES ('827', '827');
INSERT INTO menze (naziv, adresa) VALUES ('828', '828');
INSERT INTO menze (naziv, adresa) VALUES ('829', '829');
INSERT INTO menze (naziv, adresa) VALUES ('830', '830');
INSERT INTO menze (naziv, adresa) VALUES ('831', '831');
INSERT INTO menze (naziv, adresa) VALUES ('832', '832');
INSERT INTO menze (naziv, adresa) VALUES ('833', '833');
INSERT INTO menze (naziv, adresa) VALUES ('834', '834');
INSERT INTO menze (naziv, adresa) VALUES ('835', '835');
INSERT INTO menze (naziv, adresa) VALUES ('836', '836');
INSERT INTO menze (naziv, adresa) VALUES ('837', '837');
INSERT INTO menze (naziv, adresa) VALUES ('838', '838');
INSERT INTO menze (naziv, adresa) VALUES ('839', '839');
INSERT INTO menze (naziv, adresa) VALUES ('840', '840');
INSERT INTO menze (naziv, adresa) VALUES ('841', '841');
INSERT INTO menze (naziv, adresa) VALUES ('842', '842');
INSERT INTO menze (naziv, adresa) VALUES ('843', '843');
INSERT INTO menze (naziv, adresa) VALUES ('844', '844');
INSERT INTO menze (naziv, adresa) VALUES ('845', '845');
INSERT INTO menze (naziv, adresa) VALUES ('846', '846');
INSERT INTO menze (naziv, adresa) VALUES ('847', '847');
INSERT INTO menze (naziv, adresa) VALUES ('848', '848');
INSERT INTO menze (naziv, adresa) VALUES ('849', '849');
INSERT INTO menze (naziv, adresa) VALUES ('850', '850');
INSERT INTO menze (naziv, adresa) VALUES ('851', '851');
INSERT INTO menze (naziv, adresa) VALUES ('852', '852');
INSERT INTO menze (naziv, adresa) VALUES ('853', '853');
INSERT INTO menze (naziv, adresa) VALUES ('854', '854');
INSERT INTO menze (naziv, adresa) VALUES ('855', '855');
INSERT INTO menze (naziv, adresa) VALUES ('856', '856');
INSERT INTO menze (naziv, adresa) VALUES ('857', '857');
INSERT INTO menze (naziv, adresa) VALUES ('858', '858');
INSERT INTO menze (naziv, adresa) VALUES ('859', '859');
INSERT INTO menze (naziv, adresa) VALUES ('860', '860');
INSERT INTO menze (naziv, adresa) VALUES ('861', '861');
INSERT INTO menze (naziv, adresa) VALUES ('862', '862');
INSERT INTO menze (naziv, adresa) VALUES ('863', '863');
INSERT INTO menze (naziv, adresa) VALUES ('864', '864');
INSERT INTO menze (naziv, adresa) VALUES ('865', '865');
INSERT INTO menze (naziv, adresa) VALUES ('866', '866');
INSERT INTO menze (naziv, adresa) VALUES ('867', '867');
INSERT INTO menze (naziv, adresa) VALUES ('868', '868');
INSERT INTO menze (naziv, adresa) VALUES ('869', '869');
INSERT INTO menze (naziv, adresa) VALUES ('870', '870');
INSERT INTO menze (naziv, adresa) VALUES ('871', '871');
INSERT INTO menze (naziv, adresa) VALUES ('872', '872');
INSERT INTO menze (naziv, adresa) VALUES ('873', '873');
INSERT INTO menze (naziv, adresa) VALUES ('874', '874');
INSERT INTO menze (naziv, adresa) VALUES ('875', '875');
INSERT INTO menze (naziv, adresa) VALUES ('876', '876');
INSERT INTO menze (naziv, adresa) VALUES ('877', '877');
INSERT INTO menze (naziv, adresa) VALUES ('878', '878');
INSERT INTO menze (naziv, adresa) VALUES ('879', '879');
INSERT INTO menze (naziv, adresa) VALUES ('880', '880');
INSERT INTO menze (naziv, adresa) VALUES ('881', '881');
INSERT INTO menze (naziv, adresa) VALUES ('882', '882');
INSERT INTO menze (naziv, adresa) VALUES ('883', '883');
INSERT INTO menze (naziv, adresa) VALUES ('884', '884');
INSERT INTO menze (naziv, adresa) VALUES ('885', '885');
INSERT INTO menze (naziv, adresa) VALUES ('886', '886');
INSERT INTO menze (naziv, adresa) VALUES ('887', '887');
INSERT INTO menze (naziv, adresa) VALUES ('888', '888');
INSERT INTO menze (naziv, adresa) VALUES ('889', '889');
INSERT INTO menze (naziv, adresa) VALUES ('890', '890');
INSERT INTO menze (naziv, adresa) VALUES ('891', '891');
INSERT INTO menze (naziv, adresa) VALUES ('892', '892');
INSERT INTO menze (naziv, adresa) VALUES ('893', '893');
INSERT INTO menze (naziv, adresa) VALUES ('894', '894');
INSERT INTO menze (naziv, adresa) VALUES ('895', '895');
INSERT INTO menze (naziv, adresa) VALUES ('896', '896');
INSERT INTO menze (naziv, adresa) VALUES ('897', '897');
INSERT INTO menze (naziv, adresa) VALUES ('898', '898');
INSERT INTO menze (naziv, adresa) VALUES ('899', '899');
INSERT INTO menze (naziv, adresa) VALUES ('900', '900');
INSERT INTO menze (naziv, adresa) VALUES ('901', '901');
INSERT INTO menze (naziv, adresa) VALUES ('902', '902');
INSERT INTO menze (naziv, adresa) VALUES ('903', '903');
INSERT INTO menze (naziv, adresa) VALUES ('904', '904');
INSERT INTO menze (naziv, adresa) VALUES ('905', '905');
INSERT INTO menze (naziv, adresa) VALUES ('906', '906');
INSERT INTO menze (naziv, adresa) VALUES ('907', '907');
INSERT INTO menze (naziv, adresa) VALUES ('908', '908');
INSERT INTO menze (naziv, adresa) VALUES ('909', '909');
INSERT INTO menze (naziv, adresa) VALUES ('910', '910');
INSERT INTO menze (naziv, adresa) VALUES ('911', '911');
INSERT INTO menze (naziv, adresa) VALUES ('912', '912');
INSERT INTO menze (naziv, adresa) VALUES ('913', '913');
INSERT INTO menze (naziv, adresa) VALUES ('914', '914');
INSERT INTO menze (naziv, adresa) VALUES ('915', '915');
INSERT INTO menze (naziv, adresa) VALUES ('916', '916');
INSERT INTO menze (naziv, adresa) VALUES ('917', '917');
INSERT INTO menze (naziv, adresa) VALUES ('918', '918');
INSERT INTO menze (naziv, adresa) VALUES ('919', '919');
INSERT INTO menze (naziv, adresa) VALUES ('920', '920');
INSERT INTO menze (naziv, adresa) VALUES ('921', '921');
INSERT INTO menze (naziv, adresa) VALUES ('922', '922');
INSERT INTO menze (naziv, adresa) VALUES ('923', '923');
INSERT INTO menze (naziv, adresa) VALUES ('924', '924');
INSERT INTO menze (naziv, adresa) VALUES ('925', '925');
INSERT INTO menze (naziv, adresa) VALUES ('926', '926');
INSERT INTO menze (naziv, adresa) VALUES ('927', '927');
INSERT INTO menze (naziv, adresa) VALUES ('928', '928');
INSERT INTO menze (naziv, adresa) VALUES ('929', '929');
INSERT INTO menze (naziv, adresa) VALUES ('930', '930');
INSERT INTO menze (naziv, adresa) VALUES ('931', '931');
INSERT INTO menze (naziv, adresa) VALUES ('932', '932');
INSERT INTO menze (naziv, adresa) VALUES ('933', '933');
INSERT INTO menze (naziv, adresa) VALUES ('934', '934');
INSERT INTO menze (naziv, adresa) VALUES ('935', '935');
INSERT INTO menze (naziv, adresa) VALUES ('936', '936');
INSERT INTO menze (naziv, adresa) VALUES ('937', '937');
INSERT INTO menze (naziv, adresa) VALUES ('938', '938');
INSERT INTO menze (naziv, adresa) VALUES ('939', '939');
INSERT INTO menze (naziv, adresa) VALUES ('940', '940');
INSERT INTO menze (naziv, adresa) VALUES ('941', '941');
INSERT INTO menze (naziv, adresa) VALUES ('942', '942');
INSERT INTO menze (naziv, adresa) VALUES ('943', '943');
INSERT INTO menze (naziv, adresa) VALUES ('944', '944');
INSERT INTO menze (naziv, adresa) VALUES ('945', '945');
INSERT INTO menze (naziv, adresa) VALUES ('946', '946');
INSERT INTO menze (naziv, adresa) VALUES ('947', '947');
INSERT INTO menze (naziv, adresa) VALUES ('948', '948');
INSERT INTO menze (naziv, adresa) VALUES ('949', '949');
INSERT INTO menze (naziv, adresa) VALUES ('950', '950');
INSERT INTO menze (naziv, adresa) VALUES ('951', '951');
INSERT INTO menze (naziv, adresa) VALUES ('952', '952');
INSERT INTO menze (naziv, adresa) VALUES ('953', '953');
INSERT INTO menze (naziv, adresa) VALUES ('954', '954');
INSERT INTO menze (naziv, adresa) VALUES ('955', '955');
INSERT INTO menze (naziv, adresa) VALUES ('956', '956');
INSERT INTO menze (naziv, adresa) VALUES ('957', '957');
INSERT INTO menze (naziv, adresa) VALUES ('958', '958');
INSERT INTO menze (naziv, adresa) VALUES ('959', '959');
INSERT INTO menze (naziv, adresa) VALUES ('960', '960');
INSERT INTO menze (naziv, adresa) VALUES ('961', '961');
INSERT INTO menze (naziv, adresa) VALUES ('962', '962');
INSERT INTO menze (naziv, adresa) VALUES ('963', '963');
INSERT INTO menze (naziv, adresa) VALUES ('964', '964');
INSERT INTO menze (naziv, adresa) VALUES ('965', '965');
INSERT INTO menze (naziv, adresa) VALUES ('966', '966');
INSERT INTO menze (naziv, adresa) VALUES ('967', '967');
INSERT INTO menze (naziv, adresa) VALUES ('968', '968');
INSERT INTO menze (naziv, adresa) VALUES ('969', '969');
INSERT INTO menze (naziv, adresa) VALUES ('970', '970');
INSERT INTO menze (naziv, adresa) VALUES ('971', '971');
INSERT INTO menze (naziv, adresa) VALUES ('972', '972');
INSERT INTO menze (naziv, adresa) VALUES ('973', '973');
INSERT INTO menze (naziv, adresa) VALUES ('974', '974');
INSERT INTO menze (naziv, adresa) VALUES ('975', '975');
INSERT INTO menze (naziv, adresa) VALUES ('976', '976');
INSERT INTO menze (naziv, adresa) VALUES ('977', '977');
INSERT INTO menze (naziv, adresa) VALUES ('978', '978');
INSERT INTO menze (naziv, adresa) VALUES ('979', '979');
INSERT INTO menze (naziv, adresa) VALUES ('980', '980');
INSERT INTO menze (naziv, adresa) VALUES ('981', '981');
INSERT INTO menze (naziv, adresa) VALUES ('982', '982');
INSERT INTO menze (naziv, adresa) VALUES ('983', '983');
INSERT INTO menze (naziv, adresa) VALUES ('984', '984');
INSERT INTO menze (naziv, adresa) VALUES ('985', '985');
INSERT INTO menze (naziv, adresa) VALUES ('986', '986');
INSERT INTO menze (naziv, adresa) VALUES ('987', '987');
INSERT INTO menze (naziv, adresa) VALUES ('988', '988');
INSERT INTO menze (naziv, adresa) VALUES ('989', '989');
INSERT INTO menze (naziv, adresa) VALUES ('990', '990');
INSERT INTO menze (naziv, adresa) VALUES ('991', '991');
INSERT INTO menze (naziv, adresa) VALUES ('992', '992');
INSERT INTO menze (naziv, adresa) VALUES ('993', '993');
INSERT INTO menze (naziv, adresa) VALUES ('994', '994');
INSERT INTO menze (naziv, adresa) VALUES ('995', '995');
INSERT INTO menze (naziv, adresa) VALUES ('996', '996');
INSERT INTO menze (naziv, adresa) VALUES ('997', '997');
INSERT INTO menze (naziv, adresa) VALUES ('998', '998');
INSERT INTO menze (naziv, adresa) VALUES ('999', '999');
INSERT INTO menze (naziv, adresa) VALUES ('1000', '1000');
COMMIT;
SET autocommit = 1;


SHOW VARIABLES WHERE variable_name = "autocommit";

